---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki-repo
  namespace: monitoring-ns
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts

---
# ref: https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring-ns
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: loki-repo
  install:
    crds: Create
  interval: 1h
  # releaseName: loki-release
  targetNamespace: monitoring-ns
  upgrade:
    crds: CreateReplace
  # values:

