---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prom-graf-repo
  namespace: monitoring-ns
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts

---
# ref: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-graf
  namespace: monitoring-ns
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prom-graf-repo
  install:
    crds: Create
  interval: 1h
  # releaseName: prom-graf-release
  targetNamespace: monitoring-ns
  upgrade:
    crds: CreateReplace
  # values:

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingroute
  namespace: monitoring-ns
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`grafana.{server:[a-z]+}.{domain:[a-z0-9-_]+}.{tld:[a-z]+}`)
      kind: Rule
      services:
        - name: monitoring-ns-prom-graf-grafana
          port: 3000

