---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-dev
  namespace: flux-system
spec:
  dependsOn: 
  - name: infra-apps
  interval: 1m
  path: ./apps/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-prod
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-apps
  interval: 1m
  path:
    ./apps/prod
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
