---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn: 
  - name: infra-apps
  interval: 1m0s
  path: 
    ./apps/dev
    ./apps/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

