---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets-ns

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets-repo
  namespace: sealed-secrets-ns
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-ns
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
      version: '>=1.15.0-0'
  install:
    crds: Create
  interval: 1h
  releaseName: sealed-secrets-controller
  targetNamespace: sealed-secrets-ns
  upgrade:
    crds: CreateReplace
  values:
    keyrenewperiod: 0

