---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # ref: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    envFrom:
    - secretRef:
      name: traefik-acme-dns-cloudflare-secret
    persistence:
      enabled: enabled
    ports:
      web:
        redirectTo: websecure  # redirect http to https
      websecure:
        tls:
          enabled: true
          certResolver: le
          domains:
          - main: "mixtemi.com"
            sans:
            - "*.mixtemi.com"
    additionalArguments:
    - "--certificatesresolvers.le.acme.email=alo@ivgo.me"
    - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    - "--certificatesresolvers.le.acme.dnschallenge=true"
    - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: traefik-acme-dns-cloudflare-secret
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgB7Mucm5PRftjO/k8K8PfDt0H7nRydgaO8cno/JVpcUfZoZy9LTxiHjmP0j+ySiEq/kTo459Orm2JeQuvGn8W/I4rYalEM/xTSjcTaNyxra2ZC0HS9gohz3Bpl+8iN3ID9lE5gQ4OuMzYaU9q/tFpoqxxX87I0e6WMHu2Qq5gMg+GWWx8xjRKF0n5hVjUwytloRWN5FAdLWHA2sbGbPfDKXP0f9zqLtawB6vVSOtwAFPZi54tMDJqtPEMrhF3JxRZv4CDcag9Qby5vdSBgx9Ivvr50I/RvSoFuddzNVt81i8ft0m5/0KFh/QILncD7daOg5EMUylbypDBZtDbHifJcAnt/gqICHjlYpsaYcaAPLWjIH/k3iDj7l83We5i6FBxZdrew4EuwmaFncI8uCPYfr5xNRW4YbD8UjH97m4StyEDRVstBa56mdVrxIniOwMOQw5YPfOSHL5rGULYexdFrBj2BxC1230/BXIL/w1Ie+kMYxAQRehOQhxHNoRN1QqC3Y/xWZl8ReKFz6cJFvpLRSn1U5igUu273Neh4fqSNimCTdsp2zFTUPu5I7iDi9ZlZFQcY8D6kNgZ8JgGKdkj1IkH9hUFo7YSxlLHeXbe/qDCPUPhnzACEvU1AfBM077N9ZHxZN03CepGs3tJUjYi2QBd1XijHyFYyQ2DuqID/zR0r+l0kwByIfQd7Bv71WDrqTL5+0PtZMrRJSW4n++pyVFVx8rAUtDimggl0LHsCnb8lT/K78PS4b
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: traefik-acme-dns-cloudflare-secret
      namespace: kube-system

