---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # ref: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesContent: |-
    envFrom:
    - secretRef:
      name: traefik-acme-dns-cloudflare-secret
    persistence:
      enabled: enabled
    ports:
      web:
        redirectTo: websecure  # redirect http to https
      websecure:
        tls:
          enabled: true
          certResolver: le
          domains:
          - main: "mixtemi.com"
            sans:
            - "*.mixtemi.com"
    additionalArguments:
    - "--certificatesresolvers.myresolver.acme.email=alo@ivgo.me"
    - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    - "--certificatesresolvers.le.acme.dnschallenge=true"
    - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-acme-dns-cloudflare-secret
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAJR2hLm8x6C+XSVBK/DgwrCDdlUZDZvVbPoN3sXahfHu4d6z4DfdMgxTPt4jlVZ2QDM7IeA5qcX0mk9Y7m5wrEkMK/pskBAA+NsWv4cJKGjtJ5GpPgI3w7xFIrgRADZYdd4qcAfYvuKwD3TSSownICRLrqqP840cPHGr2UBCOoEVMhmFm4W1tjJnf2Ka30NDZQK0UJJJiszpKz5pIz0MdxsvddET5K6Y2TV68FJmVhIK3rFvX8F6od1GmjXv3uBkos88QAqohHXguj4E6he7vZmhQpV0slBjmU8I6Wqs/yXT0ieYVQJ1D3xz9Hl7Qb8wzsROxA+alTlw5Yg5QoDZWEWfaHvz4uFBi/vda0ORcKa9qt+a5aP3hPxLaJlF+9HO3RULE6cysbK4O9PgZQG/gbhETarhDN8xJP30vo3GBXlXULSKqWFaBnbI8KQ5CDvHsmjrkF4kB9GFdYLBIwrAC1e7FH1XMef7/9yFlL04IutM5ATkkvEV/fI93vdGZHQd/MLbbHP3TWKnQkwM/c3RmXeGx80XsU/5MzRc6nVOKD05WWT0Uf0aQRCe7Y14zMFPJR7vZe1Mlp0h/QHUJWeNRq0djoaCvq32eCSsHj+Tp05OpGF5RU/9BnPauwTDproTp+YxEuhPzbegNOjueH9g8d5jMavedtA2xVmiu0qPLN7AD647ngrdv+QRVMf+eI8R/gGn/ZBh1ABMKK0pAwEKJD2pQdvIKjR+mUu4t5oUlvUD3/unAeckVe
  template:
    metadata:
      name: traefik-acme-dns-cloudflare-secret
      namespace: kube-system
