---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: empanada-repo
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/mixtemi/empanada

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: empanada-release
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: empanada-repo

